   version: '3.1'
   services:
     db:
       image: postgres:14
       restart: always
       environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: address_matching
       ports:
         - "5432:5432"
       volumes:
         - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql